language: go

go:
- "1.13"

# $TRAVIS_GOARCH hack - see https://github.com/travis-ci/travis-ci/issues/6126

env:
  matrix:
    - TRAVIS_GOARCH=amd64
    - TRAVIS_GOARCH=386

before_install:
 - export GOARCH=$TRAVIS_GOARCH
 - sudo apt-get -y install snmp
 - export CODECOV_TOKEN="81d96f00-26df-40dd-8286-58b96fd92963"

install:
 - go get -u github.com/gosnmp/gosnmp
 - go get github.com/stretchr/testify/assert
 - go get -u golang.org/x/tools/cmd/goimports

script:
 - go build .
 - go test  -coverpkg ./...   -v ./... 
                        -coverprofile=tCoverage1.txt -covermode=atomic
 - cat tCoverage*.txt > coverage.txt
 - go build github.com/slayercat/GoSNMPServer/cmd/gosnmpserver

after_success:
 - bash <(curl -s https://codecov.io/bash)
